name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v2
    - uses: cygwin/cygwin-install-action@master
      with:
        packages: cygwin-devel,gcc-core
    - name: configure
      run: CHERE_INVOKING=1 CYGWIN_NOWINPATH=1 bash --login -c './configure'
      shell: bash
    - name: make
      run: CHERE_INVOKING=1 CYGWIN_NOWINPATH=1 bash --login -c 'make'
      shell: bash
    - name: make check
      run: CHERE_INVOKING=1 CYGWIN_NOWINPATH=1 bash --login -c 'make check'
      shell: bash
    - name: make distcheck
      run: CHERE_INVOKING=1 CYGWIN_NOWINPATH=1 bash --login -c 'make distcheck'
      shell: bash
